config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  
  resources :users
  resources :films
  resources :genres

  get 'about' => 'static_pages#about'
  get 'search' => 'films#search'

  root 'static_pages#home'

end

app/models/film.rb
class Film < ActiveRecord::Base
    belongs_to :genre
    validates :title, length: { minimum: 1, maximum: 50 }
    validates :director, length: { minimum: 1, maximum: 100 }
    validates :description, length: { minimum: 1, maximum: 2000 }
    validates :genre_id, presence: true
end

app/models/genre.rb
class Genre < ActiveRecord::Base
    has_many :films
    validates :name, length: { minimum: 1, maximum: 30 }
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :nick, presence: true, length: { maximum: 50, minimum: 3 }, uniqueness: true
    validates :password, length: { minimum: 6 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, 
        format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    #@films = Film.all
    @films = Film.paginate(:page => params[:page], :per_page => 5).order('title ASC')
  end
  
  def search
    @toSearch = params[:search]
    @films = Film.where("title LIKE ? OR description LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%").paginate(:page => params[:page], :per_page => 5).order('title ASC')
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @genres = Genre.all
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
    @genres = Genre.all
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:title, :director, :genre_id, :description)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.paginate(:page => params[:page], :per_page => 5).order('name ASC')
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(nick: params[:session][:nick])
    
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = "Nieprawidłowy login/hasło."
      render new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Witamy w Movie Share!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:nick, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def displayTitle(string = "")
       base_title = "Movie Share" 
       if string.blank?
           base_title
       else
           "#{string} | #{base_title}"
       end
    end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    #logowanie
    def log_in(user)
        session[:user_id] = user.id
    end
    
    #zwracanie usera
    def current_user
       @current_user ||= User.find_by(id: session[:user_id])
    end
    
    #czy zalogowany
    def logged_in?
       !current_user.nil?
    end
    
    #wylogowanie
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "control-label" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :director, class: "control-label" %>
    <%= f.text_field :director, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :genre_id, class: "control-label" %>
    <% options = options_from_collection_for_select(@genres, 'id', 'name') %>
    <%= f.select :genre_id,  options, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "control-label" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/films/_listing.html.erb
<% if logged_in? %>
  <p class="navbar-text navbar-right">
    <%= link_to 'Nowy Film', new_film_path, class: "navbar-link" %>
  </p>
<% end %>
<br/>
<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>



<table class="table">
  <thead>
    <tr>
      <th>Tytuł</th>
      <th>Reżyseria</th>
      <th>Gatunek</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.title %></td>
        <td><%= film.director %></td>
        <td><%= film.genre.name %></td>
        <td><%= link_to 'Pokaż', film %></td>
        <% if logged_in? %>
          <td><%= link_to 'Edytuj', edit_film_path(film) %></td>
          <td><%= link_to 'Usuń', film, method: :delete, data: { confirm: 'Jesteś pewny?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>

app/views/films/edit.html.erb
<% provide(:title, @film.title) %>
<h1>Editing Film</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<% provide(:title, "Filmy") %>
<h1>Filmy</h1>

<%= render 'films/listing' %>

app/views/films/new.html.erb
<% provide(:title, "Nowy Film") %>
<h1>Nowy Film</h1>

<%= render 'form' %>

<%= link_to 'Wróć', films_path %>

app/views/films/search.html.erb
<% provide(:title, "Wyszukiwarka") %>
<p id="notice"><%= notice %></p>

<h1>Filmy pasujące do "<%= @toSearch %>"</h1>

<%= render 'films/listing' %>

app/views/films/show.html.erb
<% provide(:title, @film.title) %>

<h1>
  <%= @film.title %>
</h1>

<div class="panel panel-default">
  <div class="panel-heading">Reżyseria</div>
  <div class="panel-body">
    <%= @film.director %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Gatunek</div>
  <div class="panel-body">
    <%= @film.genre.name %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Opis</div>
  <div class="panel-body">
    <%= @film.description %>
  </div>
</div>

<%= link_to 'Edytuj', edit_film_path(@film) %> |
<%= link_to 'Wróć', films_path %>

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "control-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<% provide(:title, @genre.name) %>
<h1>Editing Genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<% provide(:title, "Kategorie") %>
<h1>Kategorie</h1>

<% if logged_in? %>
  <p class="navbar-text navbar-right">
    <%= link_to 'Nowa Kategoria', new_genre_path %>
  </p>
<% end %>
<br/>
<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>


<table class="table">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <% if logged_in? %>
          <td><%= link_to 'Edytuj', edit_genre_path(genre) %></td>
          <td><%= link_to 'Usuń', genre, method: :delete, data: { confirm: 'Jesteś pewny?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>

app/views/genres/new.html.erb
<% provide(:title, "Nowa kategoria") %>
<h1>Nowa kategoria</h1>

<%= render 'form' %>

<%= link_to 'Wróć', genres_path %>

app/views/genres/show.html.erb
<% provide(:title, @genre.name) %>

<div class="panel panel-default">
  <div class="panel-heading">Nazwa</div>
  <div class="panel-body">
    <%= @genre.name %>
  </div>
</div>
<!--p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p-->

<%= link_to 'Edytuj', edit_genre_path(@genre) %> |
<%= link_to 'Wróć', genres_path %>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Movie Share", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form action="<%= search_path %>" class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" name="search" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Szukaj</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Filmy", films_path  %></li>
        <% if logged_in? %>
          <li><%= link_to "Kategorie", genres_path  %></li>
        <% end %>
        <li><%= link_to "O stronie", about_path  %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Konto<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profil", user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Wyloguj", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Logowanie", login_path  %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <!-- class="container-fluid navbar navbar-default navbar-fixed-top" div class="container">
    <div id="LOGO" class="navbar-header">
        <%= link_to "Movie Share", root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form action="<%= search_path %>" class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" name="search" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Szukaj</button>
      </form>

      <nav class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Filmy", films_path  %></li>
          <% if logged_in? %>
            <li><%= link_to "Kategorie", genres_path  %></li>
          <% end %>
          <li><%= link_to "O stronie", about_path  %></li>
          
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Konto<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Profil", user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Wyloguj", logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Logowanie", login_path  %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div-->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= displayTitle(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<article class="container text-left">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %>
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>
  
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</article>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "O stronie") %>

<h1>O stronie</h1>
<p>
    Portal Movie Share powstał z myślą o dzieleniu się wrażeniami na temat filmów między użytkownikami portalu. 
    Obecnie umożliwiamy poszukiwanie filmów w bazie oraz dodawanie ich i kategorii (te ostatnie po zalogowaniu). 
    Docelowo będzie można umieszczać recenzje filmów oraz zapytania o opinie na temat filmów nie będących jeszcze w bazie.
</p>

app/views/static_pages/home.html.erb
<h1>Witaj na portalu Movie Share!</h1>
<p>Dziel się swoimi opiniami na temat filmów, szukaj opinii innych by wiedzieć czy warto poświęcać swój czas. Dołącz do nas!</p>

app/views/users/new.html.erb
<% provide(:title, 'Rejestracja') %>

<h1>Rejestracja</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :nick %>
      <%= f.text_field :nick, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Stwórz konto", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Profil") %>
<h1>Profil użytkownika <%= @user.nick %></h1>

<div class="panel panel-default">
  <div class="panel-heading">email</div>
  <div class="panel-body">
    <%= @user.email %>
  </div>
</div>